#!/bin/bash
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C4 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C4/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach wo_pruning --specified_category C4 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C4/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_alone --specified_category C4 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C4/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C4 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C4/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_avg --specified_category C4 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C4/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach wo_pruning --specified_category C2 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C2/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_alone --specified_category C2 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C2/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C2 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C2/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_avg --specified_category C2 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C2/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C2 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C2/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach wo_pruning --specified_category IID --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/IID/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_alone --specified_category IID --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/IID/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category IID --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/IID/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_avg --specified_category IID --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/IID/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category IID --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/IID/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach wo_pruning --specified_category C3 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C3/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_alone --specified_category C3 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C3/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C3 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C3/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_avg --specified_category C3 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C3/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C3 --name runs/ViTWithTempCNN_prune10_client5_0.1_alpha9/C3/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C4 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C4/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach wo_pruning --specified_category C4 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C4/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_alone --specified_category C4 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C4/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C4 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C4/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_avg --specified_category C4 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C4/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach wo_pruning --specified_category C2 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C2/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_alone --specified_category C2 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C2/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C2 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C2/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_avg --specified_category C2 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C2/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C2 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C2/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach wo_pruning --specified_category IID --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/IID/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_alone --specified_category IID --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/IID/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category IID --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/IID/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_avg --specified_category IID --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/IID/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category IID --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/IID/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach wo_pruning --specified_category C3 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C3/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_alone --specified_category C3 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C3/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C3 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C3/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_avg --specified_category C3 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C3/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C3 --name runs/ViTWithTempCNN_prune20_client5_0.1_alpha9/C3/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_20.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C4 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C4/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach wo_pruning --specified_category C4 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C4/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_alone --specified_category C4 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C4/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C4 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C4/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_avg --specified_category C4 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C4/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach wo_pruning --specified_category C2 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C2/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_alone --specified_category C2 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C2/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C2 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C2/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_avg --specified_category C2 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C2/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C2 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C2/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach wo_pruning --specified_category IID --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/IID/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_alone --specified_category IID --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/IID/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category IID --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/IID/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_avg --specified_category IID --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/IID/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category IID --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/IID/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach wo_pruning --specified_category C3 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C3/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_alone --specified_category C3 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C3/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C3 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C3/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_avg --specified_category C3 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C3/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C3 --name runs/ViTWithTempCNN_prune30_client5_0.1_alpha9/C3/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_30.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C4 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C4/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach wo_pruning --specified_category C4 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C4/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_alone --specified_category C4 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C4/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C4 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C4/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_avg --specified_category C4 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C4/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach wo_pruning --specified_category C2 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C2/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_alone --specified_category C2 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C2/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C2 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C2/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_avg --specified_category C2 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C2/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C2 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C2/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach wo_pruning --specified_category IID --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/IID/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_alone --specified_category IID --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/IID/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category IID --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/IID/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_avg --specified_category IID --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/IID/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category IID --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/IID/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach wo_pruning --specified_category C3 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C3/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_alone --specified_category C3 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C3/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C3 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C3/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_avg --specified_category C3 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C3/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C3 --name runs/ViTWithTempCNN_prune40_client5_0.1_alpha9/C3/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_40.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C4 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C4/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach wo_pruning --specified_category C4 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C4/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_alone --specified_category C4 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C4/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C4 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C4/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_avg --specified_category C4 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C4/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach wo_pruning --specified_category C2 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C2/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_alone --specified_category C2 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C2/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C2 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C2/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_avg --specified_category C2 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C2/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C2 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C2/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach wo_pruning --specified_category IID --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/IID/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_alone --specified_category IID --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/IID/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category IID --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/IID/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_avg --specified_category IID --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/IID/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category IID --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/IID/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach wo_pruning --specified_category C3 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C3/wo_pruning --local_epochs 10 --epochs 1 --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_alone --specified_category C3 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C3/pruning_alone --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric js --specified_category C3 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C3/pruning_per_js --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_avg --specified_category C3 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C3/pruning_avg --pruning_config ./configs/imagenet_resnet50_prune72_50.json
python distributed_prune.py --approach pruning_per --distance_metric emd --specified_category C3 --name runs/ViTWithTempCNN_prune50_client5_0.1_alpha9/C3/pruning_per_emd --pruning_config ./configs/imagenet_resnet50_prune72_50.json
